addons:
  chrome: stable

language: node_js
node_js:
  - node

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

#before_install:
 #- export CHROME_BIN=chromium-browser

install:
  - npm install

script:
  - npm run _build-css
  - npm test
